# Generated by Django 5.1.5 on 2025-02-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('FICTION', 'Ficção'), ('NON_FICTION', 'Não Ficção'), ('ROMANCE', 'Romance'), ('MYSTERY', 'Mistério'), ('SCIFI', 'Ficção Científica'), ('FANTASY', 'Fantasia')], max_length=20)),
                ('publication_year', models.IntegerField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
