# Generated by Django 5.1.5 on 2025-02-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('FICTION', 'Ficção'), ('NON_FICTION', 'Não Ficção'), ('ROMANCE', 'Romance'), ('MYSTERY', 'Mistério'), ('DYSTOPIAN', 'Distopia'), ('SATIRE', 'Sátira'), ('MAGICAL_REALISM', 'Realismo Mágico'), ('FANTASY', 'Fantasia')], max_length=50),
        ),
    ]
