# Generated by Django 5.1.5 on 2025-02-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[
                ('FICCAO', 'Ficção'),
                ('NAO_FICCAO', 'Não Ficção'),
                ('ROMANCE', 'Romance'),
                ('MISTERIO', 'Mistério'),
                ('DISTOPIA', 'Distopia'),
                ('SATIRA', 'Sátira'),
                ('REALISMO_MAGICO', 'Realismo Mágico'),
                ('FANTASIA', 'Fantasia')
            ], max_length=50),
        ),
    ]
